### ISSUE TITLE
scroller fails to update modal colors

### ISSUE THREAD

**Issue by alexge233** [joeytwiddle/sexy_scroller.vim#14]
I use [vim-airline](https://github.com/vim-airline/vim-airline) along with `tmux`, `powerline fonts`, etc.
After installing and using `sexy_scroller` I've noticed that the modal colour does not update properly.
Quite often the colour used during `insert` will remain under `visual`, and only going into `insert` and escaping again fixes it. This is not an issue when I don't use `sexy_scroller`.
What could cause this?

**Comment by joeytwiddle** [comment]
That is interesting. I am not currently using Airline, but I also have a minor bug with one of the highlight groups in my statusline.

But I'm afraid I have no idea why this is happening.  `sexy_scroller` does not do any highlighting!

**Comment by alexge233** [comment]
I'm closing this, its not related to sexy scroller, I've disabled it and its still happening so it must be some other plugin.
